version: '3.8'

services:
  app:
    build:
      context: .
    working_dir: /var/www
    volumes:
      - './:/var/www'
    ports:
      - '8000:80'
    networks:
      - app
    depends_on:
      - webserver

  webserver:
    image: nginx:alpine
    container_name: nginx_laravel
    volumes:
      - './:/var/www'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
    networks:
      - app

networks:
  app:
    driver: bridge
